version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
           
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
         
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app